### ISSUE TITLE
Ambientar integrantes ao GitHub e ao repositório

### ISSUE THREAD

**Issue by Bruno-Felix** [fga-eps-mds/2020.1-Vamos_Cuidar#2]
Descrição:
Todos os integrantes personalizarem seus perfis e entrarem no repositório do grupo.

Tarefas:
- [x] Verificar no email o convite, feito pela @emysdias, para o repositório do grupo;
- [x] Todos terem fotos e informações em seus perfis;
- [x] Adicionarem extensão ZenHub;
- [x] Dá um fork no projeto.

Critério de Aceitação:
- [x] Todos os integrantes aceitar o convite;
- [x] Todos os integrantes personalizarem seus perfis;
- [x] Todos terem o ZenHub instalado;
- [x] Todos terem dado um fork no projeto.

**Comment by Bruno-Felix** [comment]
#2 @MesterSyned coloca seu nome em seu perfil para facilitar na hora de criar issues.

**Comment by Bruno-Felix** [comment]
#2 Reabri essa issue pelo motivo de acreditar que **dá um fork** no projeto se encaixe bem ao propósito da issue.

**Comment by DenysRogeres** [comment]
#2 Acabei tudo que foi pedido e já dei fork no projeto
