### ISSUE TITLE
Estudar o design de fluxo Gitflow

### ISSUE THREAD

**Issue by Bruno-Felix** [fga-eps-mds/2020.1-Vamos_Cuidar#20]
**Descrição**
Issue direcionada no estudo do Design de Fluxo Gitflow.

**Tarefas**
- [x] Pesquisar a essência e o uso do Gitflow;
- [x] Compartilhar as melhores referencias para estudo.

**Critério de Aceitação**
- [x] Integrantes responsáveis precisam concordar que as referencias compartilhadas são suficiente para o uso do Gitflow.

**Comment by DanielPortods** [comment]
Em uma pesquisa rápida, encontrei o seguinte <a href="https://www.atlassian.com/br/git/tutorials/comparing-workflows/gitflow-workflow"> artigo </a>.

O artigo aborda o padrão de uso do Gitflow e explica as partes com e sem o uso da extensão do git-flow.

**Comment by Bruno-Felix** [comment]
#20 Explicação em vídeo do design de fluxo Gitflow: [video](https://www.youtube.com/watch?v=wzxBR4pOTTs)
