### ISSUE TITLE
Assistir ao vídeo da reunião com o cliente

### ISSUE THREAD

**Issue by DanielPortods** [fga-eps-mds/2020.1-Vamos_Cuidar#22]
### Descrição:
Todos os integrantes devem estar bem instruídos quanto ao tema do projeto que será desenvolvido.

### Tarefas:

- [x] Assistir ao <a href="https://web.microsoftstream.com/video/f7a06339-771a-4b5b-a08a-0f09d91d86db">vídeo</a> da reunião.

- [x]  Ler a <a href = "https://github.com/fga-eps-mds/2020.1-Vamos_Cuidar/blob/develop/docs/ReuniaoComClientes.md">ata</a> da reunião.

### Critérios de aceitação:

- [x] Todos os integrantes leram a ata e assistiram ao vídeo.

**Comment by DanielPortods** [comment]
#22 Realizei todas as terefas da issue.

**Comment by enzoggqs** [comment]
#22 Também realizei todas as tarefas dessa issue.

**Comment by daniel-bm** [comment]
#22 Realizei todas as tarefas da issue.

**Comment by Bruno-Felix** [comment]
#22 Realizei todas as tarefas da issue.

**Comment by Bruno-Felix** [comment]
#22 Ainda não tinha comentado devido ao fato de eu não ter sido relacionado a issue. 

Como já diria a Pablito: "O que os olhos não veem, o coração não sente". heheheheeheheehehe

**Comment by emysdias** [comment]
#22 Assisti o vídeo e li a ata

**Comment by DenysRogeres** [comment]
#22 Eu havia participado da reunião, mas agora que eu revi o vídeo deu pra se ambientar ao tema novamente. Já vi o vídeo e li a ata.
