### ISSUE TITLE
Treinamento sobre documento de arquitetura

### ISSUE THREAD

**Issue by DanielPortods** [fga-eps-mds/2020.1-Vamos_Cuidar#23]
### Descrição:
Os batedores de #12 deverão fazer um breve treinamento com os demais integrantes baseados nas fontes compartilhadas.

### Tarefas:

- [x] Definir quando será realizado o treinamento. 

- [x] Dividir os tópicos de treinamento entre os batedores.

### Critérios de aceitação:

- [x] Treinamento ser concluído.

**Comment by DanielPortods** [comment]
@enzoggqs , visto o template inserido no repositório e as referências nele contidas, vc tem preferência em falar sobre algum tópico ou subtópico em específico?

**Comment by enzoggqs** [comment]
@DanielPortods eu prefiro falar sobre os primeiro tópicos, a introdução e a representação da arquitetura a princípio, mas podemos discutir, caso você goste mais de algum deles, ou caso vc queira q eu fique com mais tópicos.

**Comment by DanielPortods** [comment]
@enzoggqs , tudo certo então, vc fica responsável pelos tópicos 1, 2 e 3 e eu pelos 4, 5, 6 e 7. Pode ser ?

**Comment by enzoggqs** [comment]
Pode sim.

**Comment by DanielPortods** [comment]
O treinamento foi realizado em reunião pelo discord no dia 01/09.
