### ISSUE TITLE
Inserir o template do documento de arquitetura

### ISSUE THREAD

**Issue by DanielPortods** [fga-eps-mds/2020.1-Vamos_Cuidar#24]
### Descrição:
Deve ser criado e inserido um documento de arquitetura com o template que será usado e editado ao longo de todo o projeto.

### Tarefas:

- [x]  Inserir um documento de arquitetura.

### Critérios de aceitação: 

- [x] Todos os integrantes devem concordar em usar o arquivo inserido.

**Comment by Bruno-Felix** [comment]
#24 Concordo com a inserção do template do documento de arquitetura.

Só acrescentaria minha preocupação com o desenvolvimento desso documento. Pelo fato de não termos EPS e por parecer um documento trabalhoso, pode ser que gere algumas duvidas e problemas ao longo do seu desenvolvimento.

O estudo já feito junto a auxílio de outras pessoas já experientes pode ajudar.

**Comment by enzoggqs** [comment]
#24 Concordo com a utilização desse template no nosso projeto.

Acredito que a princípio, é um documento que abrange todas as nossas necessidades quanto as possíveis arquiteturas, mas ao longo do projeto, realmente podemos ter algumas dúvidas, como disse o @Bruno-Felix . Mas creio que essas dúvidas venham mais por falta experiência.

Também concordo que a procura por pessoas mais experientes nos ajudaria. Então irei a procura de pessoas que já tiveram mais contato com o documento para uma possível melhora

**Comment by emysdias** [comment]
#24 Concordo com a inserção do template do documento de arquitetura, achei bem massa

**Comment by DanielPortods** [comment]
Todos os integrantes revisaram e concordaram com o template inserido.
