### ISSUE TITLE
Treinamento sobre templates para a contribuição com o projeto

### ISSUE THREAD

**Issue by enzoggqs** [fga-eps-mds/2020.1-Vamos_Cuidar#25]
### Descrição:

Os batedores da issue #4 treinarão os outros membros acerca dos templates, com base em seus estudos.

### Tarefas:

- [x]  Divisão dos tópicos entre os batedores.
- [x]  Definir data para a realização dos treinamentos.

### Critérios de aceitação:

- [x] Conclusão do treinamento.

**Comment by Bruno-Felix** [comment]
#25 Essa issue se encaixa bem com a issue #30.

Podíamos fazer uma reunião, aonde nós mostrávamos o trabalho com o gitflow e de git (repositório local) e a passagem das mudanças do repositório do projeto(repositório remoto).

**Comment by enzoggqs** [comment]
#25 Concordo. Podemos fazer um dia pra todos esses treinamentos.

**Comment by enzoggqs** [comment]
#25 Como o @daniel-bm está sem internet esses dias, provavelmente eu serei o encarregado do treinamento do grupo.

**Comment by enzoggqs** [comment]
#25 O treinamento será realizado na noite de hoje, dia 01/09/2020

**Comment by enzoggqs** [comment]
O treinamento foi concluído!
