### ISSUE TITLE
Estudo da estrutura de uma aplicação web

### ISSUE THREAD

**Issue by emysdias** [fga-eps-mds/2020.1-Vamos_Cuidar#26]
### Descrição:
Como as tecnologias trabalham para fazer app web funcionar, como o back-end se comunicará com o front-end e com o banco de dados

### Tarefas:
- [x]  Verificar como que as tecnologias trabalham juntas

### Critérios de aceitação:
- [x]  Todos os membros do grupo devem concordar

**Comment by Bruno-Felix** [comment]
#26 Uma dica de repositório que demostra bem todo o processo de desenvolvimento: [Developer-Roadmap](https://github.com/kamranahmedse/developer-roadmap)

**Comment by emysdias** [comment]
#26 O projeto front-end se integra com o projeto back-end via API REST, enviando e devolvendo as informações no formato JSON.

Vou postar umas fotos depois

**Comment by emysdias** [comment]
#26
![sensedia-graphql-bff-1200x565](https://user-images.githubusercontent.com/52640974/91892248-ad82b600-ec68-11ea-9c35-221c14cc99d3.jpg)

**Comment by emysdias** [comment]
#26
![back](https://user-images.githubusercontent.com/52640974/91892327-d6a34680-ec68-11ea-8beb-62dce74a9cdf.png)

**Comment by emysdias** [comment]
#26
![DATASUL-REST](https://user-images.githubusercontent.com/52640974/91892400-f9355f80-ec68-11ea-97cb-d1ab1b811f71.png)

**Comment by daniel-bm** [comment]
Essa semana tive vários problemas com minha internet e ela ainda não foi normalizada então não consegui trabalhar bem nessa issue.

**Comment by daniel-bm** [comment]
Acredito que as fotos são bem intuitivas e apresentam uma boa visão geral de como o front se integra com o back.
