### ISSUE TITLE
Estudo da função Scrum Master

### ISSUE THREAD

**Issue by DenysRogeres** [fga-eps-mds/2020.1-Vamos_Cuidar#27]
### Descrição:
O integrante deve estudar as funções a ser desempenhada durante o projeto

### Tarefas:
- [x] Estudar funções e atribuições do Scrum Master

### Critérios de aceitação:

- [x] O integrante deve entender a função a ser exercida 
_____________________________________________________________________________________________________
### Scrum Master
O Scrum Master é responsável por promover e suportar o Scrum. O Scrum Master faz isso ajudando todos a entenderem a teoria, as práticas e as regras do Scrum, ou seja, ele é responsável por transmitir os valores da metodologia ágil e, por possuir esses conhecimentos, deve garantir que todos da equipe respeitem e sigam essas práticas de valores.

O Scrum Master é um servo-líder para o Time Scrum. O Scrum Master ajuda aqueles que estão
fora do Time Scrum a entender quais as suas interações com o Time Scrum são úteis e quais
não são. O Scrum Master ajuda todos a mudarem estas interações para maximizar o valor
criado pelo Time Scrum.

#### O Scrum Master trabalhando para o Product Owner
O Scrum Master serve o Product Owner de várias maneiras, incluindo:
• Garantindo que objetivos, escopo e domínio do produto sejam entendidos o melhor
possível por todos do Time Scrum
• Encontrando técnicas para o gerenciamento efetivo do Backlog do Produto;
• Ajudando o Time Scrum a entender as necessidades para ter itens de Backlog do Produto
claros e concisos.
• Compreendendo o planejamento do Produto em um ambiente empírico;
• Garantindo que o Product Owner saiba como organizar o Backlog do Produto para maximar
valor;
• Compreender e praticar a agilidade; e,
• Facilitar os eventos Scrum conforme exigidos ou necessários.

#### O Scrum Master trabalhando para o Time de Desenvolvimento
O Scrum Master serve o Time de Desenvolvimento de várias maneiras, incluindo:
• Treinando o Time de Desenvolvimento em autogerenciamento e interdisciplinaridade;
• Ajudando o Time de Desenvolvimento na criação de produtos de alto valor;
• Removendo impedimentos para o progresso do Time de Desenvolvimento;
• Transmitir os valores da metodologia ágil garantindo que todos da equipe respeitem e sigam essas práticas de valores.
• Facilitando os eventos Scrum conforme exigidos ou necessários; e,
• Treinando o Time de Desenvolvimento em ambientes organizacionais nos quais o Scrum
não é totalmente adotado e compreendido.

**Comment by Bruno-Felix** [comment]
#27 Vou criar uma nova issue para o estudo do Product Owner para conseguir usar o comentário inicial da issue como um README e escrever tudo que estudei sobre.

**Comment by DenysRogeres** [comment]
#27 Para fins de estudos em relação ao papel do Scrum Master, utilizei como referência o [Guia do Scrum](https://www.scrumguides.org/docs/scrumguide/v2017/2017-Scrum-Guide-Portuguese-Brazilian.pdf) e o curso de [Agile Development](https://www.coursera.org/programs/f79d1699-8331-48d9-a69d-2742a3db4c8c?collectionId=&productId=PAPSW6NREeWQ8xJEkcqusQ&productType=s12n&showMiniModal=true) disponibilizado pela coursera.
