### ISSUE TITLE
Conversar com Clientes

### ISSUE THREAD

**Issue by Bruno-Felix** [fga-eps-mds/2020.1-Vamos_Cuidar#29]
### Descrição:
Conversar com o pessoal do Hackathon que proveram a ideia do projeto e tentar entender, de maneira mais profunda, o tema.

### Tarefas:

**Script:**
- Conversar sobre a faculdade deles, como se reuniram e quiseram participar do evento;
- Saber o contexto e o ambiente do Hackathon; (Associar com o evento nacional Prêmio Mini Empresa 2014 que participei aonde fiquei em 3º);
- Saber tema do Hackathon e entender a ideia tida;
- Conversar sobre a problemática que eles combateram;
- Entender o processo do evento e o desenvolvimento da aplicação (Aprenderam muito?, Tiveram problemas);
- Expectativa sobre o resultado; (Tinham a sensação que podiam vencer?)
- Como foi ser campeão?
- Conversar sobre o desenvolvimento do projeto (ideias, sugestões e dicas);
- Conseguir a apresentação deles;
- Conversar sobre a logo e as imagens usadas.

### Critérios de aceitação:
- Entender melhor como foi o Hackathon e a experiencia do cliente no projeto;
- Entender melhor o tema e suas premissas;

**Comment by Bruno-Felix** [comment]
#29 PDF do regulamento do Hackathon: [Regulamento Hackathon](http://pctec.unb.br/images/Eventos/2019/FNI/Regulamento_Hackathon.pdf)

**Comment by Bruno-Felix** [comment]
#29 Foto do grupo com o Prêmio do Hackathon: [Post Facebook](https://www.facebook.com/parquetecnologico.unb/photos/a.827598257432798/1233861336806486/?type=3&eid=ARB4iBNYWNbbL1BLYUe7FoYBdwVoHXeoJEGJezCXd5L_0bfLwl6jkiItaDuQ_7NfhwaetONmrbV0W56Y&size=1080%2C1080&fbid=1233861336806486&source=13&player_origin=unknown&__xts__[0]=68.ARDXWLKxqCZT-IgrEuwRsUJpz_E67MN_hXVp8voVQxxHT67JEMvjNGJ0_rFuDKXMusm6AdnGbkJ9vq5PygzoowYivMpIAuVvO5wiM67pZ9amJQbN-cROY_FL1R6xPbRk30hg46X6iBy8lycUqzm6aA0vvT4d7wP16bCfF5iIJaP8qZFSRZNKGYiH96pWwVIhPe4DXwo9xQDEIF3sHxhqAneaBxdL-Z6q0qEZsn9LJsNm5nuqxatOe9i0aoDMmAeKA7l5QZMXy5csMqxHr4nhX0ZI7lkuyDY4Yk-gGE2nV13Ox-XFKg)

**Comment by DanielPortods** [comment]
#29 Seria interessante solicitar as imagens de logo e icones que eles usaram no modelo deles.

**Comment by DenysRogeres** [comment]
@Bruno-Felix Quando você se reunir com os ganhadores do hackathon, não esqueça de falar comigo, quero participar da reunião pra tirar algumas dúvidas.

**Comment by Bruno-Felix** [comment]
> #29 Seria interessante solicitar as imagens de logo e icones que eles usaram no modelo deles.

Ok. vou anotar isso para debatermos na reunião.

**Comment by Bruno-Felix** [comment]
> #29 @Bruno-Felix Quando você se reunir com os ganhadores do hackathon, não esqueça de falar comigo, quero participar da reunião pra tirar algumas dúvidas.

#29 Mandei a mensagem para o Bruno nesse momento, esperando retorno.

Caso consiga, vou conversar com os meninos e tentar achar um horário para se reunirmos com eles.

**Comment by emysdias** [comment]
#29 Qualquer coisa eu quero participar da reunião também, fiquei com algumas dúvidas quando eu vi o vídeo

**Comment by Bruno-Felix** [comment]
> #29 Qualquer coisa eu quero participar da reunião também, fiquei com algumas dúvidas quando eu vi o vídeo

#29 Ok. Sem problemas.

**Comment by Bruno-Felix** [comment]
> > #29 @Bruno-Felix Quando você se reunir com os ganhadores do hackathon, não esqueça de falar comigo, quero participar da reunião pra tirar algumas dúvidas.
> 
> #29 Mandei a mensagem para o Bruno nesse momento, esperando retorno.
> 
> Caso consiga, vou conversar com os meninos e tentar achar um horário para se reunirmos com eles.

#29 Contato feito, mas tem o impasse de outra pessoa estar conversando com o grupo sobre o tema.

**Comment by Bruno-Felix** [comment]
#29 Mensagem enviada para o Guilherme Aguiar.

**Comment by DenysRogeres** [comment]
#29 Caso o Guilherme marque alguma reunião com os ganhadores do hackathon, seria bom a algum de nós ir tbm. Veja a possibilidade de marcar uma reunião mensal com o pessoal do outro grupo, acredito que seja importante para deixar ambos alinhados.

**Comment by Bruno-Felix** [comment]
Ainda não está 100% garantido que o grupo da outra turma irá pegar o tema. Foi uma sugestão do professor deles.

Vamos esperar eles confirmarem de fato para fazermos outros passos.

**Comment by Bruno-Felix** [comment]
> #29 Caso o Guilherme marque alguma reunião com os ganhadores do hackathon, seria bom a algum de nós ir tbm. Veja a possibilidade de marcar uma reunião mensal com o pessoal do outro grupo, acredito que seja importante para deixar ambos alinhados.

Ainda não está 100% garantido que o grupo da outra turma irá pegar o tema. Foi uma sugestão do professor deles.

Vamos esperar eles confirmarem de fato para fazermos outros passos.

**Comment by Bruno-Felix** [comment]
Devido as descobertas dessa semana. Essa issue teve seus contratempos.

Irei esperar a resposta do grupo da outra turma sobre se realmente irão pegar o projeto ou não.

Após isso, conversaremos sobre uma reunião, em conjunto, com os clientes.

Inclusive irei fazer uma issue, na sprint seguinte, mencionando o grupo deles para essa tal reunião.
