### ISSUE TITLE
Criar discord

### ISSUE THREAD

**Issue by emysdias** [fga-eps-mds/2020.1-Vamos_Cuidar#32]
### Descrição:
Criação de discord para uma maior facilitação de comunicação

### Tarefas:
- [x]  Criar os canais de texto e de voz no discord

### Critérios de aceitação:
- [x] Todos os membros entrarem

**Comment by DanielPortods** [comment]
Recebi o convite e já estou participando do sevidor.

**Comment by emysdias** [comment]
#32 Comentem aqui que já entraram

**Comment by DenysRogeres** [comment]
#32 Já entrei no servidor do Discord.

**Comment by emysdias** [comment]
#32 Todos já entraram
