### ISSUE TITLE
Estudar e planejar nossa GitHub Page

### ISSUE THREAD

**Issue by DanielPortods** [fga-eps-mds/2020.1-Vamos_Cuidar#33]
### Descrição:
Estudar sobre criação de GitHub Pages e elaborar os tópicos que terão em nossa página.

### Tarefas:
- [ ] Entender como se cria e como funciona uma página do GitHub;
- [ ] Visualizar os principais tópicos que serão necessário na nossa GitHub page.

### Critérios de aceitação:
- [ ] Compartilhar as melhores referencias para estudo;
- [x] Ter a lista dos principais tópicos que estarão na nossa GitHub page;
*  _Deverá ser compartilhada por essa issue._;
- [ ] Integrantes responsáveis concordam que as referências compartilhadas são suficiente;
- [ ] Integrantes responsáveis concordam com a lista de tópicos estarão na nossa GitHub page.

**Comment by DanielPortods** [comment]
Uma ótima iniciação ao tema se econtra nesse <a href="https://guides.github.com/features/pages/">guia</a>.

**Comment by Bruno-Felix** [comment]
#33 Durante o estudo de Product Owner, tive a curiosidade de estudar como tudo elaborado pelo papel se linkava ao longo do projeto. E nisso visualizei as pages dos grupos anteriores. Me inseri nessa issue por achar que ela pode ter uma vertente a mais no nosso projeto.

Podemo já aqui planejar os documentos e tópicos que estarão na nossa GitHub page.

**Comment by Bruno-Felix** [comment]
#33 Minha lista de documentos e tópicos que podem fazer parte da nossa page:

Lembrando que nem tudo o que foi elaborado pelos grupos anteriores pode ser feito nosso nosso pelo fato de ter pessoas unicamente encarregadas de gerar aqueles documentos, infos e tópicos entre eles(EPS). Temos que ter foco no que é crucial para nós.

Lista:
- Documento de Visão #6;
- Documento de Arquitetura #12;
- Identidade Visual (desejável mas não crucial);
- Product Backlog #19 #34;
- Roadmap do Produto; (Falta estudo)
- Protótipo #13.
- Gerenciamento de Sprints #14 #27;
- Contribuição #4 #5.

Por favor, visualizem outras pages e comentem o que acham que devem estar na nossa page. Assim também poderemos ver o que falta para estudarmos.

**Comment by DenysRogeres** [comment]
#33 Para estudos, utilizei o guia disponibilizado pelo @DanielPortods e este [video](https://www.youtube.com/watch?v=bj3ZFzKiIXw&t=92s) que encontrei no youtube.

**Comment by Bruno-Felix** [comment]
Concordo com todos as referencias levantas aqui.

Seguindo a issue #3, Os grupos Acacia e ADA fizeram uma branch especifica para github page.

Acredito que essa seja uma solução mais simples para a hospedagem da página. Particularmente não gosto da ideia de ter múltiplos repositórios. Como é um projeto acadêmico, quanto mais as infos e ações estiverem juntas e visíveis, melhor, na minha opinição.

**Comment by DanielPortods** [comment]
Concordo com a lista de tópico, acho que ficou bem completa. 

Acredito que todas as referências levantadas aqui são o bastante e concordo com a opinião do @Bruno-Felix sobre a hospedagem da página.

**Comment by DenysRogeres** [comment]
Concordo com as referências feitas e a acredito que listagem feita pelo @Bruno-Felix esteja bem completa.

**Comment by daniel-bm** [comment]
As referências são muito boas e a lista feita pelo @Bruno-Felix está bem completa.
