### ISSUE TITLE
Estudo, levantamento e debate de requisitos

### ISSUE THREAD

**Issue by DanielPortods** [fga-eps-mds/2020.1-Vamos_Cuidar#38]
### Descrição:
Para auxiliar um melhor entendimento e aprofundamento dos aspectos do projeto, os integrante devem se inteirar sobre levantamento de requisitos visto possível contato com cliente. 

### Tarefas:

- [x] Estudar sobre levantamento de requisitos.

- [x] levantar requisitos dos projeto com o que temos até agora. (para efeito de treino)

- [x] Realizar reunião dia 05/09 19 horas.

### Critérios de aceitação:

- [x] Debater todos os requisitos pensados pelos integrantes.

- [ ] Criar issue para desenvolvimento do documento de arquitetura.

- [x] Criar issue do desenvolvimento do Product Backlog.

## Requisitos
Identificador | Requisito
-- | --
RF01 | Permitir que usuários da comunidade acadêmica realize postagens sobre problemas da universidade
RF02 | Permitir o usuário editar e excluir suas postagens
RF03 | Permitir que o usuário crie, edite e apaga sua conta
RF04 | Permitir o usuário fazer e desfazer login de sua conta
RF05 | Exibir a listagem de todas as postagens feitas
RF06 | Permitir a visualização de todas informações de uma postagem
RF07 | Permitir que o usuário visualize suas postagens feitas
RF08 | Permitir a visualização do estágio de resolução da postagem
RF09 | Permitir que a listagem das postagens seja feita por filtros
RF10 | Permitir os usuários engajarem com uma postagem, através de comentários e apoio(positivo ou negativo)
RF11 | Permitir o usuário compartilhar uma postagem
RF12 | Permitir o reporte de uma postagem
RF13 | Exibir ao usuário uma notificação caso uma postagem sua tenha sido resolvida com sucesso
RF14 | Exibir uma página direcionada às notificações e atualizações da universidade sobre as postagens
RF15 | Exibir uma aba de ajuda de uso da aplicação
RNF16 | A aplicação deve fazer a verificação de conta com dados da universidade
RNF17 | O sistema deve se tratar de uma PWA (Progressive web app)
RNF18 | A aplicação deve ter uma experiencia de uso simples e familiar, de linguagem fácil e intuitiva
RNF19 | Assegurar a segurança de dados dos usuários
RNF20 | Pode ter suporte para gamificação

**Comment by daniel-bm** [comment]
Achei que este [artigo](https://medium.com/lfdev-blog/como-escrever-requisitos-de-software-de-forma-simples-e-garantir-o-m%C3%ADnimo-de-erros-no-sistema-app-74df2ee241cc) e este [vídeo](https://www.youtube.com/watch?v=VcOeM2AD8Yk&ab_channel=B%C3%B3sonTreinamentos) explicam bem o tema.

**Comment by DanielPortods** [comment]
> Achei que este [artigo](https://medium.com/lfdev-blog/como-escrever-requisitos-de-software-de-forma-simples-e-garantir-o-m%C3%ADnimo-de-erros-no-sistema-app-74df2ee241cc) e este [vídeo](https://www.youtube.com/watch?v=VcOeM2AD8Yk&ab_channel=B%C3%B3sonTreinamentos) explicam bem o tema.

Muito bom esse vídeo, conteúdo de ótima qualidade. Removeu muito do bloqueio que eu estava tendo no assunto. Mostra que não é um bixo de sete cabeças.

**Comment by DanielPortods** [comment]
#### Eu adorei isso aqui:
:sweat_smile: :stuck_out_tongue_winking_eye:
![Balanço](https://miro.medium.com/max/640/0*lAwHB9RgIT7lOXt9.jpg)

**Comment by DanielPortods** [comment]
A reunião foi realizada conforme previsto e todos os integrantes debetaram sobre os requisitos levantados por cada um.
Houve um consenso entre todos sobre a seguinte listagem:


## REQUISITOS FUNCIONAIS:

**RF01** – O sistema deve permitir que estudantes e servidores realizem postagens sobre problemas no dia a dia da universidade, com imagens e texto; 
**RF02** – O sistema deve permitir que estudantes e servidores se engajem em outras postagens; 
**RF03** – O grau de engajamento deve ser fator de cálculo para o posicionamento da postagem no feed; 
**RF04** – O sistema deve conter uma página direcionada às notícias da universidade; 
**RF05** – Caso haja algum sistema de gamificação, o sistema deve realizar notificação por e-mail para os colaboradores          que postarem os problemas resolvidos; 
**RF06** – O sistema deve permitir o compartilhamento de postagens individuais
**RF07** – O sistema deve permitir que estudantes, e servidores se engajem em postagens tanto positivamente quanto negativamente; 
**RF08** – O sistema deve permitir que estudantes, servidores e administração realizem comentários nas publicações; 
**RF09** – O sistema deve permitir a qualquer um reportar conteúdos impróprios.

## REQUISITOS NÃO FUNCIONAIS:

**RNF01** – O sistema deve se tratar de uma PWA (Progressive web app); 
**RNF02** – Deve ter uma estrutura simples e familiar com linguagem fácil e intuitiva;
**RNF03** – Qualquer cadastro deve ser rápido e simples;
**RNF04** – Estudantes não devem ter acesso aos dados de outro estudante;
**RNF05** – Pode ter suporte para gamificação.

**Comment by Bruno-Felix** [comment]
> A reunião foi realizada conforme previsto e todos os integrantes debetaram sobre os requisitos levantados por cada um.
> Houve um consenso entre todos sobre a seguinte listagem:
> 
> ## REQUISITOS FUNCIONAIS:
> **RF01** – O sistema deve permitir que estudantes e servidores realizem postagens sobre problemas no dia a dia da universidade, com imagens e texto;
> **RF02** – O sistema deve permitir que estudantes e servidores se engajem em outras postagens;
> **RF03** – O grau de engajamento deve ser fator de cálculo para o posicionamento da postagem no feed;
> **RF04** – O sistema deve conter uma página direcionada às notícias da universidade;
> **RF05** – Caso haja algum sistema de gamificação, o sistema deve realizar notificação por e-mail para os colaboradores que postarem os problemas resolvidos;
> **RF06** – O sistema deve permitir o compartilhamento de postagens individuais
> **RF07** – O sistema deve permitir que estudantes, e servidores se engajem em postagens tanto positivamente quanto negativamente;
> **RF08** – O sistema deve permitir que estudantes, servidores e administração realizem comentários nas publicações;
> **RF09** – O sistema deve permitir a qualquer um reportar conteúdos impróprios.
> 
> ## REQUISITOS NÃO FUNCIONAIS:
> **RNF01** – O sistema deve se tratar de uma PWA (Progressive web app);
> **RNF02** – Deve ter uma estrutura simples e familiar com linguagem fácil e intuitiva;
> **RNF03** – Qualquer cadastro deve ser rápido e simples;
> **RNF04** – Estudantes não devem ter acesso aos dados de outro estudante;
> **RNF05** – Pode ter suporte para gamificação.

Revisão e atualização dos Requisitos:

## Requisitos do Produto

| Identificador | Requisito |
| :-    | :-  |
| RF01 | Permitir que usuários da comunidade acadêmica realize postagens sobre problemas da universidade |
| RF02 | Permitir o usuário editar e excluir suas postagens |
| RF03 | Permitir que o usuário crie, edite e apaga sua conta |
| RF04 | Permitir o usuário fazer e desfazer login de sua conta |
| RF05 | Exibir a listagem de todas as postagens feitas |
| RF06 | Permitir a visualização de todas informações de uma postagem |
| RF07 | Permitir que o usuário visualize suas postagens feitas |
| RF08 | Permitir a visualização do estágio de resolução da postagem |
| RF09 | Permitir que a listagem das postagens seja feita por filtros |
| RF10 | Permitir os usuários engajarem com uma postagem, através de comentários e apoio(positivo ou negativo) |
| RF11 | Permitir o usuário compartilhar uma postagem |
| RF12 | Permitir o reporte de uma postagem |
| RF13 | Exibir ao usuário uma notificação caso uma postagem sua tenha sido resolvida com sucesso |
| RF14 | Exibir uma página direcionada às notificações e atualizações da universidade sobre as postagens |
| RF15 | Exibir uma aba de ajuda de uso da aplicação |
| RNF16 | A aplicação deve fazer a verificação de conta com dados da universidade |
| RNF17 | O sistema deve se tratar de uma PWA (Progressive web app) | 
| RNF18 | A aplicação deve ter uma experiencia de uso simples e familiar, de linguagem fácil e intuitiva |
| RNF19 | Assegurar a segurança de dados dos usuários |
| RNF20 | Pode ter suporte para gamificação |

**Comment by Bruno-Felix** [comment]
> > A reunião foi realizada conforme previsto e todos os integrantes debetaram sobre os requisitos levantados por cada um.
> > Houve um consenso entre todos sobre a seguinte listagem:
> > ## REQUISITOS FUNCIONAIS:
> > **RF01** – O sistema deve permitir que estudantes e servidores realizem postagens sobre problemas no dia a dia da universidade, com imagens e texto;
> > **RF02** – O sistema deve permitir que estudantes e servidores se engajem em outras postagens;
> > **RF03** – O grau de engajamento deve ser fator de cálculo para o posicionamento da postagem no feed;
> > **RF04** – O sistema deve conter uma página direcionada às notícias da universidade;
> > **RF05** – Caso haja algum sistema de gamificação, o sistema deve realizar notificação por e-mail para os colaboradores que postarem os problemas resolvidos;
> > **RF06** – O sistema deve permitir o compartilhamento de postagens individuais
> > **RF07** – O sistema deve permitir que estudantes, e servidores se engajem em postagens tanto positivamente quanto negativamente;
> > **RF08** – O sistema deve permitir que estudantes, servidores e administração realizem comentários nas publicações;
> > **RF09** – O sistema deve permitir a qualquer um reportar conteúdos impróprios.
> > ## REQUISITOS NÃO FUNCIONAIS:
> > **RNF01** – O sistema deve se tratar de uma PWA (Progressive web app);
> > **RNF02** – Deve ter uma estrutura simples e familiar com linguagem fácil e intuitiva;
> > **RNF03** – Qualquer cadastro deve ser rápido e simples;
> > **RNF04** – Estudantes não devem ter acesso aos dados de outro estudante;
> > **RNF05** – Pode ter suporte para gamificação.
> 
> Revisão e atualização dos Requisitos:
> 
> ## Requisitos do Produto
> **Identificador**	**Requisito**
> RF01	Permitir que usuários da comunidade acadêmica realize postagens sobre problemas da universidade
> RF02	Permitir o usuário editar e excluir suas postagens
> RF03	Permitir que o usuário crie, edite e apaga sua conta
> RF04	Permitir o usuário fazer e desfazer login de sua conta
> RF05	Exibir a listagem de todas as postagens feitas
> RF06	Permitir a visualização de todas informações de uma postagem
> RF07	Permitir que o usuário visualize suas postagens feitas
> RF08	Permitir a visualização do estágio de resolução da postagem
> RF09	Permitir que a listagem das postagens seja feita por filtros
> RF10	Permitir os usuários engajarem com uma postagem, através de comentários e apoio(positivo ou negativo)
> RF11	Permitir o usuário compartilhar uma postagem
> RF12	Permitir o reporte de uma postagem
> RF13	Exibir ao usuário uma notificação caso uma postagem sua tenha sido resolvida com sucesso
> RF14	Exibir uma página direcionada às notificações e atualizações da universidade sobre as postagens
> RF15	Exibir uma aba de ajuda de uso da aplicação
> RNF16	A aplicação deve fazer a verificação de conta com dados da universidade
> RNF17	O sistema deve se tratar de uma PWA (Progressive web app)
> RNF18	A aplicação deve ter uma experiencia de uso simples e familiar, de linguagem fácil e intuitiva
> RNF19	Assegurar a segurança de dados dos usuários
> RNF20	Pode ter suporte para gamificação

O tópico 5 do documento de visão são os requisitos do produto. #41 
O Product Backlog tem que ser feito com base nos requisitos. #46

**Comment by Bruno-Felix** [comment]
Após uma breve discussão: O Critério de Avaliação - "Criar issue para desenvolvimento do documento de arquitetura" ficou para a próxima Sprint.
