### ISSUE TITLE
Estudo e levantamento de tecnologias/Front-end

### ISSUE THREAD

**Issue by DenysRogeres** [fga-eps-mds/2020.1-Vamos_Cuidar#39]
### Descrição:
Para fazer um bom projeto, é necessário estudar e levantar tecnologias que melhor se encaixam no projeto.
### Tarefas:

- [x] Estudar tecnologias que podem ser usadas no Front-end.

- [x] Conversar com monitor e outras pessoas sobre qual tecnologia foi escolhida em projetos passados.
  
### Critérios de aceitação:

- [x] Listar ao menos 2 tecnologias por parte da arquitetura.

- [x] Debater as tecnologias levantadas na reunião de quarta, 20h (#43).

**Comment by DanielPortods** [comment]
Vi nesse <a href="https://youtu.be/Gmiz-j_K340?t=429">video</a> que o react tem uma funcionalidade chamada localStorage. Ela permite que se armazenem informações em memória local. Pode ser útil visto os requisitos RF04 e RNF18 em #38.

**Comment by DenysRogeres** [comment]
Estudei um pouco sobre Vue.Js, AngularJS e React Js (que não é um framework). Dentre essas três ferramentas, destaco o uso do React Js por acreditar que se encaixar melhor em nosso projeto.

**Comment by DenysRogeres** [comment]
Penso também que é muito importante a gente pensar na experiência do usuário e na responsividade do nosso projeto.

**Comment by DenysRogeres** [comment]
Entrei em contato com dois amigos, um já trabalha na área e o outro está a um semestre para formar na Fga.

**Comment by DenysRogeres** [comment]
Nossa reunião aconteceu hoje 20h e foi até 21:20. Dentre as pautas discutidas, uma foi sobre as tecnologias do Front-End.
