### ISSUE TITLE
Criar perfil de comunidade Open Source

### ISSUE THREAD

**Issue by Bruno-Felix** [fga-eps-mds/2020.1-Vamos_Cuidar#4]
Descrição:
Visualizar todos os requisitos de trabalho open source.

Tarefas:
- [x] Modificar nome do repositório após termos nosso tema;
- [x] Inserir descrição;
- [x] Inserir README;
- [x] Inserir código de conduta;
- [x] Inserir Contributing;
- [x] Inserir Issue e Pull request templates.

Critérios de Aceitação:
- Todos os documentos tem que estar na língua portuguesa.
- Todos os membros concordarem com os documentos criados e mudanças feitas;

**Comment by RochaCarla** [comment]
Falta:

- [ ] detalhar as tarefas

- [ ]  definir um criterio de aceitação objetivo

- [ ] e alocar soh pra 1 ou 2 integrantes (se todo mundo é responsável, ninguém faz)

**Comment by enzoggqs** [comment]
Código de Conduta
Propósito
O projeto é mantido por estudantes durante a execução da disciplina Métodos de Desenvolvimento de Software, do curso Engenharia de Software da Universidade de Brasília. Portanto, é de suma importância promover um ambiente aberto e acolhedor. Nosso fará o possível para manter o propósito do projeto, e alcançar nosso objetivo perante a comunidade.
Nossas Responsabilidades
Os mantenedores deste projeto são responsáveis por prestar esclarecimentos em casos de dúvidas relacionadas ao código de conduta e também por ações em resposta a comportamentos inadequados. No caso de testemunhar comportamentos inadequados, estes devem ser reportados imediatamente, sendo os responsáveis do repositório obrigados a manter confidencialidade sobre a pessoa que reportar.
Exemplos de comportamentos esperados e que contribuem com o projeto
Uso de linguagem acolhedora e inclusiva
Respeito aos diferentes pontos de vista
Aceitar críticas construtivas
Demonstrar empatia com os membros da comunidade
Exemplos de comportamentos inaceitáveis
Uso de conotações sexuais
Comentários depreciativos que ataquem pessoas ou grupos
Assédio público ou privado
Publicação de conteúdo privado de terceiro sem prévia autorização
Outras condutas consideradas inapropriadas em um ambiente profissional
Escopo
Esse Código de Conduta é aplicado dentro do projeto e em locais públicos onde um indivíduo esteja representando o projeto ou sua comunidade. Exemplos são um e-mail oficial sobre o projeto, ou participação em eventos como representante.
Atribuição
Esse código de conduta é uma adaptação de Contributor Covenant, version 1.4, disponível em http://contributor-covenant.org/version/1/4

**Comment by Bruno-Felix** [comment]
#4 O arquivo CONTRIBUTING.md, inserido na #18, não foi desenvolvido. Foi inserido no repositório pelo caráter único de exclusivo de ser uma tarefa desta Issue. É necessário que a #5, a #4 e o grupo se alinhem de maneira mais completa e complexa para o desenvolvimento do documento com exatidão.

@enzoggqs todo e **qualquer ponto fora do padrão esperado**(Nesse caso, do documento está 100% desenvolvido) **tem que ser comentado** para que todos os **responsáveis** pela issue e as demais pessoas entendem exatamente o que você **fez ou não fez e porque**. Só assim, posse-se tomar as próximas ações baseadas nessa informação(nesse caso, o desenvolvimento do CONTRIBUTING.md na Sprint 1).

**Comment by daniel-bm** [comment]
#4 O contributing necessita de um padrão de branch, issues, commits e pull request que se relacionam com as issues #5 e #20.

**Comment by daniel-bm** [comment]
#4 Criei um template para issues no geral e um para issues relacionadas a algum bug.

**Comment by emysdias** [comment]
> #4 Criei um template para issues no geral e um para issues relacionadas a algum bug.

Beleza, mandou bem

**Comment by Bruno-Felix** [comment]
#4 Bom trabalho. Só faltou acrescentar os templates de Issue e Pull Request por... Pull request. kkk

Violando assim o padrão de contribuição elaborada na issue #5.

**Comment by enzoggqs** [comment]
Muito bem @daniel-bm !!
