### ISSUE TITLE
Estudo da tecnologia/Docker

### ISSUE THREAD

**Issue by emysdias** [fga-eps-mds/2020.1-Vamos_Cuidar#40]
### Descrição:
Estudar o funcionamento do docker, e como será aplicar no projeto.

### Tarefas:

- [x]  Estudar como o docker funciona para Web

### Critérios de aceitação:

- [x] Debater sobre o uso do docker na reunião de quarta, 20h (#43).

**Comment by emysdias** [comment]
#40 Uma imagem que explica a diferença de VM para DOCKER

![docker](https://user-images.githubusercontent.com/52640974/92543957-1cd94680-f223-11ea-962a-09d8343db474.png)

**Comment by emysdias** [comment]
#40 

![dock02](https://user-images.githubusercontent.com/52640974/92544038-4abe8b00-f223-11ea-8d7a-ce7333ef5377.png)

**Comment by emysdias** [comment]
#40

**Virtual Machine**

Brevemente falando, a virtualização de máquina consiste em empacotar determinada aplicação em um modelo padrão com seu próprio ambiente operacional. Assim, agora independente da máquina que você for rodar esta aplicação suas configurações serão as mesmas desde o nível de SO até as bibliotecas e dependências necessárias.

Voltemos a arquitetura de cluster de banco de dados. Você possui uma estrutura dividida com Load Balance entre 10 VPs. Todas elas precisam ter o mesmo funcionamento e configuração. Agora imagine você ter que fazer isto uma a uma manualmente… Já deu pra sentir uma gota de suor escorrendo pelo rosto neh?! Com o uso da virtualização estas configurações seguirão automaticamente o modelo feito. Além disto você pode facilitar sua vida utilizando um gerenciador de máquinas virtuais como o Vagrant.


**Containers**

O container também faz empacotamento, mas, no caso, ele não virtualizará o ambiente todo da máquina. Ele trabalhará em cima da aplicação e suas dependências criando uma virtualização apenas a nível do SO e não da máquina. Desta forma você terá o benefício de rodar ambientes isolados dentro de uma única VPs, por exemplo. Além disto você terá o benefício sobre o tamanho do sistema virtual, já que ele só integrará as configurações da sua aplicação e não da máquina inteira. Para este conceito sem dúvida hoje o maior exemplo seria o docker. Pelo seu caráter aberto, simples e colaborativo ele se tornou o sinônimo de container.

**Comment by daniel-bm** [comment]
Muito interessante essa diferença entre a VM e o Docker.

**Comment by daniel-bm** [comment]
Acho que esse [vídeo](https://www.youtube.com/watch?v=AVNADGzXrrQ&ab_channel=Rocketseat) explica muito bem.
