### ISSUE TITLE
Desenvolvimento do documento de visão

### ISSUE THREAD

**Issue by Bruno-Felix** [fga-eps-mds/2020.1-Vamos_Cuidar#41]
### Descrição:
Issue destinada para a desenvolvimento do documento de visão.

Como não temos uma visão fixa e detralhada do projeto devido a consecutivos adiamentos de reuniões com clientes, **somente os 3 primeiros tópicos do documento serão desenvolvidos**.

### Tarefas:
- [x] Desenvolver Tópico 1 - @DenysRogeres e @emysdias;
- [x] Desenvolver Tópico 2 - @Bruno-Felix e @daniel-bm;    
- [x] Desenvolver Tópico 3 - @DanielPortods e @enzoggqs;
- Comentar prováveis alterações do documento;

### Critérios de aceitação:
- [x] Todos devem aceitar o Tópico 1 desenvolvido;
- [x] Todos devem aceitar o Tópico 2 desenvolvido;    
- [x] Todos devem aceitar o Tópico 3 desenvolvido;
- Prováveis alterações comentadas devem ser discutidas.

**Comment by DanielPortods** [comment]
@enzoggqs , temos um total de 9 subtópicos. Tem alguma preferência?

**Comment by enzoggqs** [comment]
@daniel-bm posso ficar do 3.1 ao 3.4 se você não achar ruim.

**Comment by DanielPortods** [comment]
> @daniel-bm posso ficar do 3.1 ao 3.4 se você não achar ruim.

Combinado.

**Comment by Bruno-Felix** [comment]
- Acredito que nosso Documento de Visão esteja básico demais em certos pontos, muito pode ser baseado no fato de não termos tido reuniões com cliente nessas 2 ultimas semanas;
- Tópico 2.0 também é comentável;
- Tópico 1 e 2 podem ser melhor desenvolvidos.
