### ISSUE TITLE
Estudo e levantamento de tecnologias/Back-end

### ISSUE THREAD

**Issue by Bruno-Felix** [fga-eps-mds/2020.1-Vamos_Cuidar#42]
### Descrição
Issue destinada ao estudo e levantamento de tecnologias mais usadas no Back-end de uma aplicação web.

### Tarefas
- [x] Estudar tecnologias que podem ser usadas no Back-end;
- [ ] Conversar com monitor e outras pessoas sobre qual tecnologia foi escolhida em projetos passados.

### Critérios de aceitação:
- [x] Listar ao menos 2 tecnologias;
- [x] Debater as tecnologias levantadas na reunião de quarta, 20h (#43).

**Comment by Bruno-Felix** [comment]
Com base numa pesquisa rápida, percebi que as duas tecnologias mais usadas no back-end de uma aplicação web atualmente são:
- Node js, framework em JS;
   - [Vídeo - Alura](https://www.youtube.com/watch?v=GKR6uSvEj8w&ab_channel=AluraCursosOnline);
   - [Vídeo - Código Fonte TV](https://www.youtube.com/watch?v=vYekSMBCCiM&ab_channel=C%C3%B3digoFonteTV).
- Django, framework em Python:
   - [Vídeo - Código Fonte TV](https://www.youtube.com/watch?v=ao8pCrRqKOs&ab_channel=C%C3%B3digoFonteTV).

Particularmente tenho experiencia com Django, na quarentena fiz um CRUD básico com o framework. É bem simples de se usar e com pouco código se consegue fazer muita coisa. Observando projetos anteriores em MDS, Django talvez seja o mais usado e incentivado.

**Comment by Bruno-Felix** [comment]
> Com base numa pesquisa rápida, percebi que as duas tecnologias mais usadas no back-end de uma aplicação web atualmente são:
> 
> * Node js, framework em JS;
>   
>   * [Vídeo - Alura](https://www.youtube.com/watch?v=GKR6uSvEj8w&ab_channel=AluraCursosOnline);
>   * [Vídeo - Código Fonte TV](https://www.youtube.com/watch?v=vYekSMBCCiM&ab_channel=C%C3%B3digoFonteTV).
> * Django, framework em Python:
>   
>   * [Vídeo - Código Fonte TV](https://www.youtube.com/watch?v=ao8pCrRqKOs&ab_channel=C%C3%B3digoFonteTV).
> 
> Particularmente tenho experiencia com Django, na quarentena fiz um CRUD básico com o framework. É bem simples de se usar e com pouco código se consegue fazer muita coisa. Observando projetos anteriores em MDS, Django talvez seja o mais usado e incentivado.

**Comment by enzoggqs** [comment]
Achei muito interessantes os vídeos citados pelo @Bruno-Felix Bruno. Eu nunca tive contato com essas tecnologias, mas gostei muito delas e acredito que podem ser muito eficientes no nosso projeto. São tecnologias muito eficazes, que não necessitam de tanto código para vermos algum resultado, como @Bruno-Felix disse.
