### ISSUE TITLE
Estudo e levantamento de sistemas/Banco de dados

### ISSUE THREAD

**Issue by Bruno-Felix** [fga-eps-mds/2020.1-Vamos_Cuidar#44]
### Descrição:
Issue destinada ao estudo e levantamento de sistemas de gerenciamento de banco de dados mais usadas em aplicações.

### Tarefas:
- [x] Estudar sistemas de banco de dados que podem ser usados em nossa aplicação;
- [ ] Conversar com monitor e outras pessoas sobre qual sistema foi escolhido em projetos passados.

### Critérios de aceitação:
- [x] Listar ao menos 2 sistemas;
- [x] Debater os sistemas levantados na reunião de quarta, 20h (#43).

**Comment by DanielPortods** [comment]
Lembrei que, há muito tempo, eu fiz esse <a href="https://www.softblue.com.br/site/curso/id/3/CURSO+DE+SQL+COMPLETO+BASICO+AO+AVANCADO+ON+LINE+BD03+GRATIS">curso grástis</a> de SQL. Como é uma liguagem quase que obrigatória para bancos de dados relacionais, acredito que seja interessante cursar. 
Tem carga horária de 20 horas, eu vou refazer visto que não lembro de muita coisa. :sweat_smile:

**Comment by Bruno-Felix** [comment]
Pesquisei sobre banco de dados não relacionais.
Como a professora já comentou, a priori iremos usar bastante JSON, e bancos não relacionais são bem eficientes nisso.

Vídeo sobre os bancos não relacionais: [Vídeo - Código Fonte TV](https://www.youtube.com/watch?v=1B64oqE8PLs&ab_channel=C%C3%B3digoFonteTV)

E fazendo uma busca, o MongoDB é sem duvidas o mais conhecido e usado nesse seguimento de banco de dados.

**Comment by Bruno-Felix** [comment]
> Lembrei que, há muito tempo, eu fiz esse [curso grástis](https://www.softblue.com.br/site/curso/id/3/CURSO+DE+SQL+COMPLETO+BASICO+AO+AVANCADO+ON+LINE+BD03+GRATIS) de SQL. Como é uma liguagem quase que obrigatória para bancos de dados relacionais, acredito que seja interessante cursar.
> Tem carga horária de 20 horas, eu vou refazer visto que não lembro de muita coisa.

Interessante, caso usemos o SQL, já tem um local para estudo.

**Comment by Bruno-Felix** [comment]
> Pesquisei sobre banco de dados não relacionais.
> Como a professora já comentou, a priori iremos usar bastante JSON, e bancos não relacionais são bem eficientes nisso.
> 
> Vídeo sobre os bancos não relacionais: [Vídeo - Código Fonte TV](https://www.youtube.com/watch?v=1B64oqE8PLs&ab_channel=C%C3%B3digoFonteTV)
> 
> E fazendo uma busca, o MongoDB é sem duvidas o mais conhecido e usado nesse seguimento de banco de dados.

Esqueci de comentar o fator facilidade de estudo do Mongo DB. Mongo DB É relacionado a documento e como os dados trocados serão em JSON, a curva de aprendizado e uso é bem baixa.
